spring: 
  application:
    name: eureka-two

---
spring:
  profiles: peer1
  
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      #设置与eureka server 交互的地址
      default-zone: http://peer2:8762/eureka/        
    #是否将自己注册到eureka server
    register-with-eureka: true
    fetch-registry: true
---
spring:
  profiles: peer2
  
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      #设置与eureka server 交互的地址
      default-zone: http://peer1:8761/eureka/ 
    #是否将自己注册到eureka server
    register-with-eureka: true
    fetch-registry: true