server:
  port: 8000
  
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo 
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver