server:
  port: 8010
spring: 
  application:
    name: consumer
    
eureka: 
  client: 
    service-url:
      default-zone: http://user:password123@localhost:8761/eureka/
  instance: 
    prefer-ip-address: true
    appname: consumer
logging: 
  level:
      com.insightcredit.consumer.dao.UserFeignClient: DEBUG