server:
  port: 8001
  
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo 
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: provider
    
eureka: 
  client: 
    service-url:
      default-zone: http://localhost:8761/eureka/ 
  instance: 
    prefer-ip-address: true
    appname: user-provider
    virtual-host-name: user-provider